def seed_fixed_algorithms(root):
    from pathlib import Path

    def write_module(path: Path, content: str):
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(content, encoding='utf-8')
    write_module(root / 'encoding' / 'huffman_known_weights.py', '# semantic: Huffman codebook for FIXED known symbol weights per session\n# fixed.profile: telemetry_skewed_symbols\n# fixed.distribution: categorical i.i.d.; weights static within session\n# fixed.business: compress repeated telemetry / game event codes\n# advantage.vs: fixed_width_code\n# advantage.margin: bits/symbol -> H(X) vs ceil(log2(K))\n# io.in: symbols:list, weights:dict\n# io.out: codebook:dict, expected_bits:float\n\ndef huffman_known_weights(ctx):\n    data = ctx.setdefault("data", {})\n    ctx.setdefault("meta", {})\n    ctx.setdefault("state", {})\n    ctx.setdefault("error", None)\n    symbols = data.get("symbols") or []\n    weights = data.get("weights") or {}\n    if not symbols or not weights:\n        data["codebook"] = {}\n        data["expected_bits"] = 0.0\n        return ctx\n    import heapq\n    nodes = [[w, [s, ""]] for s, w in weights.items() if s in symbols]\n    heapq.heapify(nodes)\n    while len(nodes) > 1:\n        a = heapq.heappop(nodes)\n        b = heapq.heappop(nodes)\n        for pair in a[1:]:\n            pair[1] = "0" + pair[1]\n        for pair in b[1:]:\n            pair[1] = "1" + pair[1]\n        heapq.heappush(nodes, [a[0] + b[0]] + a[1:] + b[1:])\n    codebook = {sym: code for sym, code in nodes[0][1:]}\n    total = sum(weights.values()) or 1.0\n    expected = sum(weights[s] * len(codebook.get(s, "")) for s in codebook) / total\n    data["codebook"] = codebook\n    data["expected_bits"] = float(expected)\n    return ctx\n')
    write_module(root / 'encoding' / 'run_length_sparse_alphabet.py', '# semantic: Run-length encoding when alphabet size K is FIXED and runs are common\n# fixed.profile: sparse_run_events\n# fixed.distribution: symbols from fixed alphabet; P(run) high, i.i.d. across frames\n# fixed.business: delta logging of repeated game states / blank frames\n# advantage.vs: raw_symbol_stream\n# advantage.margin: O(run) storage vs O(n) when run-length >> 1\n# io.in: symbols:list\n# io.out: rle_pairs:list\n\ndef run_length_sparse_alphabet(ctx):\n    data = ctx.setdefault("data", {})\n    ctx.setdefault("meta", {})\n    ctx.setdefault("state", {})\n    ctx.setdefault("error", None)\n    symbols = data.get("symbols") or []\n    if not symbols:\n        data["rle_pairs"] = []\n        return ctx\n    pairs = []\n    cur = symbols[0]\n    count = 1\n    for s in symbols[1:]:\n        if s == cur:\n            count += 1\n        else:\n            pairs.append([cur, count])\n            cur = s\n            count = 1\n    pairs.append([cur, count])\n    data["rle_pairs"] = pairs\n    return ctx\n')
    write_module(root / 'vision' / 'grid_cell_reader.py', '# semantic: Read FIXED grid cell at (row,col) from uniform screen buffer\n# fixed.profile: ocr_fixed_hud_grid\n# fixed.distribution: pixel patches i.i.d. noise; cell layout static across sessions\n# fixed.business: OCR game HUD / logger UI with fixed template positions\n# advantage.vs: full_screen_ocr\n# advantage.margin: O(1) cell crop vs O(W*H) when layout is known\n# io.in: frame:bytes, row:int, col:int, cell_w:int, cell_h:int\n# io.out: cell_patch:bytes\n\ndef grid_cell_reader(ctx):\n    data = ctx.setdefault("data", {})\n    ctx.setdefault("meta", {})\n    ctx.setdefault("state", {})\n    ctx.setdefault("error", None)\n    frame = data.get("frame") or b""\n    row = int(data.get("row") or 0)\n    col = int(data.get("col") or 0)\n    cell_w = int(data.get("cell_w") or 1)\n    cell_h = int(data.get("cell_h") or 1)\n    if not frame:\n        data["cell_patch"] = b""\n        return ctx\n    width = int(data.get("width") or max(cell_w, 1))\n    start = (row * cell_h) * width + (col * cell_w)\n    end = start + cell_w * cell_h\n    data["cell_patch"] = frame[start:end] if start < len(frame) else b""\n    return ctx\n')
    write_module(root / 'analytics' / 'histogram_delta_encode.py', '# semantic: Delta-encode FIXED-bin histogram when totals drift slowly\n# fixed.profile: game_stat_histogram\n# fixed.distribution: bin counts change slowly frame-to-frame; bin edges FIXED\n# fixed.business: game analytics / stat aggregation with stable schema\n# advantage.vs: raw_histogram_json\n# advantage.margin: sparse deltas vs full vector when drift is small\n# io.in: prev_counts:list, counts:list\n# io.out: deltas:list\n\ndef histogram_delta_encode(ctx):\n    data = ctx.setdefault("data", {})\n    ctx.setdefault("meta", {})\n    ctx.setdefault("state", {})\n    ctx.setdefault("error", None)\n    prev = data.get("prev_counts") or []\n    cur = data.get("counts") or []\n    n = max(len(prev), len(cur))\n    deltas = []\n    for i in range(n):\n        a = prev[i] if i < len(prev) else 0\n        b = cur[i] if i < len(cur) else 0\n        deltas.append(b - a)\n    data["deltas"] = deltas\n    return ctx\n')
