def validate_compiler_adapter_stem_util(stem: str) -> bool:
    stems = frozenset(
        {
            "shared_ctx",
            "invoke_llm",
            "extract_json",
            "persist_leaf",
            "leaf_stub",
            "recall_code",
            "render_reuse",
            "conftest_setup",
            "verify_generated",
            "write_leaf_test_bridge",
            "format_io_bridge",
            "normalize_io_bridge",
            "evaluate_split_bridge",
            "seq_io_repair",
            "format_runtime_error",
            "runtime_logging",
            "save_job_tree",
            "store_tree",
            "ensure_job_scaffold",
            "assess_job",
            "verify_code",
            "verify_shared_code",
            "resume_code_tree",
            "run_one_job",
            "register_leaf",
            "write_leaf_test",
            "ensure_conftest",
            "verify_test",
            "hybrid_retrieve",
            "recall_for_reuse",
            "all_too_similar_to_parent",
            "test_path_for_leaf",
            "repair_node_code_path",
            "render_test",
            "assign_topology",
            "estimate_split_count",
            "probe_split_count",
            "render_topology_templates",
            "verify_workplace_bridge",
        }
    )
    if stem in stems:
        return True
    return stem.endswith("_bridge")
