from .context_builder import context_builder

def build_prompt(node, root=None):
    context = context_builder(node, root=root)
    fn = context['function_name']
    shared = context['shared_module_prefix']
    used_by_block = '\n'.join((f'- {x}' for x in context['used_by'])) or '- (root or standalone leaf)'
    template_imports = '\n'.join((f'- {x}' for x in context['imports_from_template'])) or '- none'
    allowed = ', '.join(context['allowed_imports'])
    shared_guide = context.get('shared_usage_guide') or ''
    return f"""\nYou are generating a Python leaf module for a generated project.\n\nSEMANTIC:\n{context['semantic']}\n\nPARENT CONTEXT:\n- parent module: {context['parent_function'] or '(none)'}\n- parent semantic: {context['parent_semantic'] or '(none)'}\n- parent topology: {context['parent_topology'] or '(none)'}\n- parent io.in: {context['parent_io_in']}\n- parent io.out: {context['parent_io_out']}\n\nDATA TYPES (ctx[\"data\"], name:type):\n- read io.in: {context['io_in']}\n- write io.out: {context['io_out']}\n\nIMPORT / USED-BY (auto from template, do NOT violate):\n- allowed imports: {allowed}\n- shared usage guide (semantic summary; do not treat as file list):\n{shared_guide}\n- example (logging): from {shared}.logging.logging_util import logging_util\n- example (validate): from {shared}.validate.types_util import types_util; from {shared}.validate.error_util import error_util\n- example (debug/profile): from {shared}.debug.debug_util import debug_util; from {shared}.debug.profile_util import profile_util\n- example (lib): from {shared}.lib.time_util import time_util; from {shared}.lib.id_util import id_util\n- example (io): from {shared}.io.path_util import path_util; from {shared}.io.file_util import file_util\n- forbidden: stdlib direct import, relative imports, subpackages, business logic in shared, any non-shared import (only __init__.py may import direct children)\n- this module used by:\n{used_by_block}\n- parent template already contains:\n{template_imports}\n\nOUTPUT FORMAT:\n# semantic: {context['semantic']}\n# io.in: {context['io_in']}\n# io.out: {context['io_out']}\n\ndef {fn}(ctx):\n    ...\n\nRULES:\n- Output ONLY valid Python\n- Exactly ONE top-level function named {fn} (same as file stem)\n- Leaf file: ONLY {shared} imports anywhere in the file (no stdlib, no relative, no business packages)\n- Respect name:type when reading/writing ctx[\"data\"]\n- Return ctx\n"""
